### ISSUE TITLE
Implement .gitignore

### ISSUE THREAD

**Issue by xedre** [discord-python/hacktoberbot#13]
Implement .gitignore for files to be ignored during push and pull

- [ ] implement .gitignore
- [ ] add logs to .gitignore

**Comment by danieldeveloper001** [comment]
Please, take a look at pull request #20 and let me know it there is something that has to be changed!

**Comment by heavysaturn** [comment]
hi @danieldeveloper001, and thanks for the pull request! I'm not entirely sure if you're a member of our discord community, if you are I'm sorry to say that this issue was already claimed by @xedre in the #event-hacktoberfest channel before your PR came in. If you are not, please note that we require all pull requests for this repo to be made by members of the community (this is explained in the `CONTRIBUTING.md` file).

@xedre's solution is also more comprehensive, and includes valuable documentation, which he was asked to include in the same PR. So I'm going to have to close your PR and accept his instead.

If you're not a member of our community already, please consider joining it. We're the largest Python community on Discord, and we have all sorts of events and features that may interest you, including an upcoming code jam with prizes.

**Comment by danieldeveloper001** [comment]
@heavysaturn, if his solution is better, that's fine, no hard feelings!
also, you're right, not a member right now, but I'll take a look at your community and maybe join it.

best regards!
